FROM node:24-alpine

WORKDIR /CRM

COPY ./package*.json ./

COPY ./apps/frontend/package*.json ./apps/frontend/

RUN npm install --only=dev

COPY ./apps/frontend ./apps/frontend

CMD ["npm", "run", "start:front"]